CREATE TABLE `USUARIO` (
  `NOMBRE` varchar(255) PRIMARY KEY,
  `CORREO` varchar(255) UNIQUE,
  `PASSWORD` varchar(255) NOT NULL,
  `IS_ADMIN` boolean NOT NULL
);

CREATE TABLE `FORO` (
  `ID` int PRIMARY KEY AUTO_INCREMENT,
  `ADMIN_ID` varchar(255)
);

CREATE TABLE `HILO` (
  `ID` int PRIMARY KEY AUTO_INCREMENT,
  `IS_PARTIDA` varchar(255) NOT NULL,
  `TITULO` varchar(255) NOT NULL,
  `AUTOR_ID` varchar(255) NOT NULL
);

CREATE TABLE `PARTIDA` (
  `ID` int PRIMARY KEY,
  `PRIVADA` boolean NOT NULL,
  `MASTER_ID` varchar(255)
);

CREATE TABLE `FICHA_JUGADOR` (
  `ID` int PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `DESCRIPCION` varchar(255),
  `CLASE` varchar(255),
  `RAZA` varchar(255),
  `TIPO` boolean NOT NULL,
  `PROPIETARIO_ID` varchar(255)
);

CREATE TABLE `FICHA_MUNDO` (
  `ID` int PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `DESCRIPCION` varchar(255),
  `TIPO` varchar(255),
  `PARTIDA_ID` int
);

CREATE TABLE `MENSAJE` (
  `ID` int PRIMARY KEY AUTO_INCREMENT,
  `TEXTO` varchar(255),
  `HILO_ID` int NOT NULL,
  `AUTOR_ID` varchar(255) NOT NULL
);

CREATE TABLE `PARTIDA_JUGADORES` (
  `PARTIDAS_JUGADOR_ID` int NOT NULL,
  `JUGADORES_ID` varchar(255) NOT NULL
);

CREATE TABLE `FORO_HILOS` (
  `FORO_ID` int NOT NULL,
  `HILOS_ID` int NOT NULL
);

CREATE TABLE `FORO_PARTIDAS` (
  `FORO_ID` int NOT NULL,
  `PARTIDAS_ID` int NOT NULL
);

ALTER TABLE `FORO` ADD FOREIGN KEY (`ADMIN_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `HILO` ADD FOREIGN KEY (`AUTOR_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `PARTIDA` ADD FOREIGN KEY (`ID`) REFERENCES `HILO` (`ID`);

ALTER TABLE `PARTIDA` ADD FOREIGN KEY (`MASTER_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `FICHA_JUGADOR` ADD FOREIGN KEY (`PROPIETARIO_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `FICHA_MUNDO` ADD FOREIGN KEY (`PARTIDA_ID`) REFERENCES `PARTIDA` (`ID`);

ALTER TABLE `MENSAJE` ADD FOREIGN KEY (`HILO_ID`) REFERENCES `HILO` (`ID`);

ALTER TABLE `MENSAJE` ADD FOREIGN KEY (`AUTOR_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `PARTIDA_JUGADORES` ADD FOREIGN KEY (`PARTIDAS_JUGADOR_ID`) REFERENCES `PARTIDA` (`ID`);

ALTER TABLE `PARTIDA_JUGADORES` ADD FOREIGN KEY (`JUGADORES_ID`) REFERENCES `USUARIO` (`NOMBRE`);

ALTER TABLE `FORO_HILOS` ADD FOREIGN KEY (`FORO_ID`) REFERENCES `FORO` (`ID`);

ALTER TABLE `FORO_HILOS` ADD FOREIGN KEY (`HILOS_ID`) REFERENCES `HILO` (`ID`);

ALTER TABLE `FORO_PARTIDAS` ADD FOREIGN KEY (`FORO_ID`) REFERENCES `FORO` (`ID`);

ALTER TABLE `FORO_PARTIDAS` ADD FOREIGN KEY (`PARTIDAS_ID`) REFERENCES `PARTIDA` (`ID`);
